### ISSUE TITLE
demo down

### ISSUE THREAD

**Issue by onno-timmerman** [MicroPyramid/Django-CRM#390] opened 2020-05-29 07:27 UTC
You demo site is down

**Comment by rjschave** [comment] 2020-06-02 04:13
Duplicate of #366 & #375?

**Comment by MindfulMe** [comment] 2020-06-07 17:44
Here is the demo for you guys:

https://crm.citvy.com/

Credentials:
email: alice.gogolauri@gmail.com
password: q363602qwE

Feel free to explore user functionality. Admin is not available for you :) Sign in works, no signup though for now. We will add registration for you via https://citvy.com so signup is going to be working in several hours. 🤟

**Comment by wancheng** [comment] 2020-09-08 04:11
https://crm.citvy.com/ is down

**Comment by ashwin31** [comment] 2020-09-08 05:46
it's bottlecrm.com. check readme for more details.

**Closed by ashwin31** 2020-09-08 05:46 UTC

**Comment by ashwin31** [comment] 2020-09-08 05:47
@wancheng it's https://bottlecrm.com. check readme for more details.
